/// Logging is a logging API intended to let users emit log messages with
/// simple priority levels, a message, and optional contextual attributes.
interface logging {
  use types.{tags};

    /// A log level, describing a kind of message.
    enum level {
       /// Describes messages likely to be of interest to someone debugging a
       /// program.
       debug,

       /// Describes messages likely to be of interest to someone monitoring a
       /// program.
       info,

       /// Describes messages indicating hazardous situations.
       warn,

       /// Describes messages indicating serious errors.
       error
    }

    /// Adds contextual attributes to the current log context.
    ///
    /// Subsequent `log` calls will include the list of tags introduced here.
    set-tags: func(tags: tags);

    /// Emit a log message.
    ///
    /// A log message has a `level` describing what kind of message is being
    /// sent, a string containing the message text, and an optional list of tags.
    log: func(level: level, message: string, tags: option<tags>);
}
